language: cpp
cache: apt
compiler:
 - gcc
 - clang
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y cmake liblapack-dev libblas-dev
before_script: 
  - mkdir build
  - cd build
script: cmake -DBUILD_EXAMPLES=ON -DBUILD_TEST=ON .. && make
after_script:
  - ./GeometricTools_test
  - ./

notifications:
  email:
    recipients:
    - costashatz@gmail.com
    on_success: change
    on_failure: always